+api for adding money, reserving money
ikhabibullin/balance pull request #9
Opened 2023-01-31 15:29 UTC by ikhabibullin

+Добавил алхимию
+Добавил модельки для баланса и для Резервирования денег
+Добавил апишки для добавления денег и для резервирования
? Как можно по другому сделать возврат ошибки в /reserve
? в services.reserve_money я прямо в функции объявляю сессию с транзакцией, ее еще можно получить в api через Depend, как лучше

2023-02-02 15:12 UTC, abstractart requested changes

2023-02-02 15:12 UTC, abstractart commented on src/services.py
> +    insert_q = insert(Balance).values(values)
Перед увеличением баланса мб все таки нужно сделать lock конкретной строчки? 

https://postgrespro.ru/docs/postgresql/9.6/explicit-locking#locking-rows -  SELECT FOR UPDATE

2023-02-02 15:12 UTC, abstractart commented on src/services.py
> +            if balance.money >= data.money:
Аналогично проблеме выше, ты вычитаешь баланс и сравниваешь значение но при этом у тебя например происходит еще одно снятие баланса, без лока баланс может уйти в минус

2023-02-02 15:12 UTC, abstractart commented on tests/test_api.py
> +def test_add_money_create():
почему решил перейти на тесты через локалхост вместо встроенного TestClient

2023-02-02 15:12 UTC, abstractart commented on src/services.py
> +async def add_money(user_id: UUID4, money: PositiveInt, session: AsyncSession) -> Row:
давай сделаем класс BankService и чтоб это были его функции

BankService должен через конструктор явно принимать свои зависимости ( коннект к бД итп)

Потом покрой его тестами

2023-02-02 15:14 UTC, abstractart commented on src/services.py
> +async def add_money(user_id: UUID4, money: PositiveInt, session: AsyncSession) -> Row:
если что то трудно потестить то застабь компонент

2023-02-07 12:58 UTC, ikhabibullin commented
@abstractart 
в сервисах занес все в класс сервиса
тесты перенес в src, потому что при запуске тестов не находил код который в приложении

вместо стандартного клиента для тестирования использую httpx клиент, потому что стандартный каждый запрос создает новый цикл событий(если я правильно понял) и это приводит к ошибке когда делаются запросы в бд, был вариант использовать NullPool параметр в engine алхимии, мне больше понравился вариант с другим клиентом

лок строки используется, проверил, работает как ожидается

2023-02-12 09:24 UTC, merged